spring:
  datasource:
    url: jdbc:mysql://mysql:3306/chefonline
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    root: ERROR
    br.com.fiap.tech.challenge.grupo.vinte.oito.ChefOnline: INFO
  file:
    name: /var/log/chefonline/application.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
